/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class myjni_Test */

#ifndef _Included_myjni_Test
#define _Included_myjni_Test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     myjni_Test
 * Method:    add
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_myjni_Test_add
  (JNIEnv *, jobject, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
